#!/usr/bin/env bash


# # Set aliases
# alias ux='chmod u+x';
# alias ax='chmod a+x';


# Begin work session
function start_session {
	git checkout master;
	git fetch upstream master;
	git merge upstream/master;
	git push;
	git status;
	echo;
	echo 'Ready to develop!';
	echo 'Please proceed...';
}

function commit_work {
	# git add $1;
	# -m is for adding a message
	# to commit
	git commit -a -m 'another update';
	git push;
}

# End work session 
function end_session {
	echo 'Pusing git...';
	git push origin master;	
	echo 'Push complete!';
	echo 'Goodbye ~';
}


function test_func {
	echo 'working';
}

start_session;