[u'One', u'night', u'it', u'was', u'on', u'the', u'twentieth', u'of', u'March', u', ', u'1888', u'I', u'was']
[u'returning', u'from', u'a', u'journey', u'to', u'a', u'patient', u' (', u'for', u'I', u'had', u'now', u'returned', u'to']
[u'civil', u'practice', u'), ', u'when', u'my', u'way', u'led', u'me', u'through', u'Baker', u'Street', u'. ', u'As', u'I']
[u'passed', u'the', u'well', u'remembered', u'door', u', ', u'which', u'must', u'always', u'be', u'associated']
[u'in', u'my', u'mind', u'with', u'my', u'wooing', u', ', u'and', u'with', u'the', u'dark', u'incidents', u'of', u'the']
[u'Study', u'in', u'Scarlet', u', ', u'I', u'was', u'seized', u'with', u'a', u'keen', u'desire', u'to', u'see', u'Holmes']
[u'again', u', ', u'and', u'to', u'know', u'how', u'he', u'was', u'employing', u'his', u'extraordinary', u'powers', u'.']
[u'His', u'rooms', u'were', u'brilliantly', u'lit', u', ', u'and', u', ', u'even', u'as', u'I', u'looked', u'up', u', ', u'I', u'saw']
[u'his', u'tall', u', ', u'spare', u'figure', u'pass', u'twice', u'in', u'a', u'dark', u'silhouette', u'against']
[u'the', u'blind', u'. ', u'He', u'was', u'pacing', u'the', u'room', u'swiftly', u', ', u'eagerly', u', ', u'with', u'his', u'head']
[u'sunk', u'upon', u'his', u'chest', u'and', u'his', u'hands', u'clasped', u'behind', u'him', u'. ', u'To', u'me', u', ', u'who']
[u'knew', u'his', u'every', u'mood', u'and', u'habit', u', ', u'his', u'attitude', u'and', u'manner', u'told', u'their']
[u'own', u'story', u'. ', u'He', u'was', u'at', u'work', u'again', u'. ', u'He', u'had', u'risen', u'out', u'of', u'his']
[u'drug', u'created', u'dreams', u'and', u'was', u'hot', u'upon', u'the', u'scent', u'of', u'some', u'new']
[u'problem', u'. ', u'I', u'rang', u'the', u'bell', u'and', u'was', u'shown', u'up', u'to', u'the', u'chamber', u'which']
[u'had', u'formerly', u'been', u'in', u'part', u'my', u'own', u'.']
[]


Trigraphs
upon his  :  [u'chest']
chest and  :  [u'his']
rooms were  :  [u'brilliantly']
.  I  :  [u'rang']
be associated  :  [u'in']
a dark  :  [u'silhouette']
.  He  :  [u'was', u'had']
a patient  :  [u' (']
the twentieth  :  [u'of']
habit,   :  [u'his']
to know  :  [u'how']
the room  :  [u'swiftly']
wooing,   :  [u'and']
of the  :  [u'Study']
had risen  :  [u'out']
risen out  :  [u'of']
my mind  :  [u'with']
a keen  :  [u'desire']
of his  :  [u'drug']
his head  :  [u'sunk']
the well  :  [u'remembered']
seized with  :  [u'a']
keen desire  :  [u'to']
up to  :  [u'the']
story.   :  [u'He']
tall,   :  [u'spare']
figure pass  :  [u'twice']
me,   :  [u'who']
even as  :  [u'I']
bell and  :  [u'was']
formerly been  :  [u'in']
had formerly  :  [u'been']
my own  :  [u'.']
mind with  :  [u'my']
been in  :  [u'part']
his drug  :  [u'created']
way led  :  [u'me']
),  when  :  [u'my']
to see  :  [u'Holmes']
I was  :  [u'returning', u'seized']
twentieth of  :  [u'March']
,  spare  :  [u'figure']
his attitude  :  [u'and']
part my  :  [u'own']
against the  :  [u'blind']
civil practice  :  [u'), ']
their own  :  [u'story']
dreams and  :  [u'was']
and manner  :  [u'told']
His rooms  :  [u'were']
up,   :  [u'I']
with the  :  [u'dark']
clasped behind  :  [u'him']
spare figure  :  [u'pass']
was returning  :  [u'from']
the Study  :  [u'in']
work again  :  [u'. ']
1888 I  :  [u'was']
upon the  :  [u'scent']
for I  :  [u'had']
passed the  :  [u'well']
drug created  :  [u'dreams']
.  As  :  [u'I']
know how  :  [u'he']
his extraordinary  :  [u'powers']
of some  :  [u'new']
with a  :  [u'keen']
how he  :  [u'was']
looked up  :  [u', ']
head sunk  :  [u'upon']
me through  :  [u'Baker']
Baker Street  :  [u'. ']
associated in  :  [u'my']
powers.  :  [u'His']
had now  :  [u'returned']
Study in  :  [u'Scarlet']
to a  :  [u'patient']
chamber which  :  [u'had']
,  with  :  [u'his']
created dreams  :  [u'and']
and with  :  [u'the']
I had  :  [u'now']
pass twice  :  [u'in']
door,   :  [u'which']
pacing the  :  [u'room']
my wooing  :  [u', ']
every mood  :  [u'and']
swiftly,   :  [u'eagerly']
,  I  :  [u'was', u'saw']
was pacing  :  [u'the']
which had  :  [u'formerly']
returning from  :  [u'a']
with my  :  [u'wooing']
again.   :  [u'He']
rang the  :  [u'bell']
which must  :  [u'always']
on the  :  [u'twentieth']
who knew  :  [u'his']
extraordinary powers  :  [u'.']
mood and  :  [u'habit']
silhouette against  :  [u'the']
some new  :  [u'problem']
and was  :  [u'hot', u'shown']
desire to  :  [u'see']
problem.   :  [u'I']
room swiftly  :  [u', ']
see Holmes  :  [u'again']
saw his  :  [u'tall']
own.  :  ['PP']
eagerly,   :  [u'with']
with his  :  [u'head']
I looked  :  [u'up']
well remembered  :  [u'door']
to civil  :  [u'practice']
,  1888  :  [u'I']
him.   :  [u'To']
lit,   :  [u'and']
were brilliantly  :  [u'lit']
was employing  :  [u'his']
was shown  :  [u'up']
through Baker  :  [u'Street']
scent of  :  [u'some']
always be  :  [u'associated']
blind.   :  [u'He']
remembered door  :  [u', ']
returned to  :  [u'civil']
March,   :  [u'1888']
,  eagerly  :  [u', ']
a journey  :  [u'to']
dark silhouette  :  [u'against']
own story  :  [u'. ']
practice),   :  [u'when']
behind him  :  [u'. ']
in a  :  [u'dark']
,  his  :  [u'attitude']
incidents of  :  [u'the']
Holmes again  :  [u', ']
. His  :  [u'rooms']
the blind  :  [u'. ']
manner told  :  [u'their']
employing his  :  [u'extraordinary']
shown up  :  [u'to']
again,   :  [u'and']
the chamber  :  [u'which']
,  which  :  [u'must']
.  To  :  [u'me']
I passed  :  [u'the']
he was  :  [u'employing']
in part  :  [u'my']
and habit  :  [u', ']
 ( for  :  [u'I']
and to  :  [u'know']
it was  :  [u'on']
I saw  :  [u'his']
new problem  :  [u'. ']
the dark  :  [u'incidents']
He had  :  [u'risen']
when my  :  [u'way']
To me  :  [u', ']
,  who  :  [u'knew']
night it  :  [u'was']
his chest  :  [u'and']
journey to  :  [u'a']
my way  :  [u'led']
dark incidents  :  [u'of']
hands clasped  :  [u'behind']
must always  :  [u'be']
his hands  :  [u'clasped']
As I  :  [u'passed']
patient  (  :  [u'for']
out of  :  [u'his']
his every  :  [u'mood']
to the  :  [u'chamber']
and,   :  [u'even']
One night  :  [u'it']
was on  :  [u'the']
,  and  :  [u'with', u'to', u', ']
sunk upon  :  [u'his']
Scarlet,   :  [u'I']
and his  :  [u'hands']
was hot  :  [u'upon']
,  even  :  [u'as']
now returned  :  [u'to']
at work  :  [u'again']
attitude and  :  [u'manner']
was seized  :  [u'with']
of March  :  [u', ']
He was  :  [u'pacing', u'at']
I rang  :  [u'the']
his tall  :  [u', ']
in Scarlet  :  [u', ']
the bell  :  [u'and']
the scent  :  [u'of']
was at  :  [u'work']
told their  :  [u'own']
from a  :  [u'journey']
in my  :  [u'mind']
twice in  :  [u'a']
led me  :  [u'through']
knew his  :  [u'every']
brilliantly lit  :  [u', ']
Street.   :  [u'As']
as I  :  [u'looked']
hot upon  :  [u'the']



I was
His rooms
Baker Street
Study in
I had
I looked
March, 
Holmes again
I passed
I saw
He had
To me
As I
One night
Scarlet, 
He was
I rang
Street. 
